packages: []
allowBuilds:
  edgedriver: true
  esbuild: true
  geckodriver: true
  protobufjs: true
  sharp: true
overrides:
  gh-pages: ">=5.0.0"
  protobufjs: ">=7.5.5"
  sharp: ">=0.35.4"
  js-yaml: ">=4.3.2"
  fast-uri: ">=3.1.6"
  ini: ">=1.3.6"
  nanoid: ">=3.3.18"
  semver: ">=6.3.1"
