/**
 * R-12 + R-11: 前端代码混淆 + 资源完整性校验 (SRI) 生成脚本
 *
 * 构建后执行：
 * 1. 对 dist/assets/*.js 进行 javascript-obfuscator 混淆
 * 2. 计算混淆后的 SHA-256 哈希
 * 3. 生成 src-tauri/src/generated/sri_hashes.rs 供 Rust 编译时嵌入
 *
 * 用法: node scripts/obfuscate-and-sri.mjs
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs'
import { join, resolve, dirname } from 'node:path'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const distAssets = resolve(root, 'dist', 'assets')
const generatedDir = resolve(root, 'src-tauri', 'src', 'generated')

// Skip obfuscation in dev mode
if (process.env.TAURI_ENV_DEBUG) {
  console.log('[obfuscate-and-sri] Debug mode — skipping obfuscation and SRI generation')
  process.exit(0)
}

// Skip if dist/assets doesn't exist
if (!existsSync(distAssets)) {
  console.warn('[obfuscate-and-sri] dist/assets not found — skipping')
  process.exit(0)
}

// ============ R-12: 代码混淆 ============

let JavaScriptObfuscator
try {
  JavaScriptObfuscator = (await import('javascript-obfuscator')).default
} catch {
  console.warn('[obfuscate-and-sri] javascript-obfuscator not installed — skipping obfuscation')
}

// 混淆选项说明（2026-08-14 调整）：
// controlFlowFlattening / selfDefending / splitStrings / transformObjectKeys 等高危选项
// 在 ESM + 动态 import 场景下会产生运行时损坏代码（字符串数组解码失败 ->
// 调用不存在的函数 -> TypeError: xxx is not a function -> 窗口加载崩溃闪现消失）。
// 降级为 stringArray 基础混淆（仍能隐藏字符串常量与标识符），保留 SRI 完整性校验。
const OBFUSCATOR_OPTIONS = {
  compact: true,
  controlFlowFlattening: false,
  deadCodeInjection: false,
  debugProtection: false,
  identifierNamesGenerator: 'hexadecimal',
  renameGlobals: false,
  selfDefending: false,
  simplify: true,
  splitStrings: false,
  stringArray: true,
  stringArrayCallsTransform: false,
  stringArrayEncoding: ['base64'],
  stringArrayIndexShift: true,
  stringArrayRotate: true,
  stringArrayShuffle: true,
  stringArrayThreshold: 0.6,
  transformObjectKeys: false,
  unicodeEscapeSequence: false,
}

if (JavaScriptObfuscator) {
  const jsFiles = readdirSync(distAssets).filter((f) => f.endsWith('.js'))
  let obfuscatedCount = 0

  for (const file of jsFiles) {
    const filePath = join(distAssets, file)
    const code = readFileSync(filePath, 'utf8')

    // Skip already minified vendor chunks to save time
    // 注意：rolldown-runtime 是各 chunk（含 vendor-*）共享的 ESM 互操作基础设施，
    // vendor chunk 通过具名导出按名绑定引用它。混淆该 chunk 会破坏 CJS 互操作
    // 语义，导致启动期 TypeError（Cannot read properties of undefined (reading 'S')）。
    // 因此必须一并跳过，保持其字节与 vendor chunk 的导入契约一致。
    const isVendor = file.startsWith('vendor-') || file.startsWith('rolldown-runtime-')
    if (isVendor) {
      console.log(`[obfuscate-and-sri] Skipping vendor chunk: ${file}`)
      continue
    }

    try {
      const obfuscated = JavaScriptObfuscator.obfuscate(code, {
        ...OBFUSCATOR_OPTIONS,
        // Smaller chunks get lighter obfuscation
        ...(code.length < 5000 ? { controlFlowFlattening: false, stringArray: false } : {}),
      }).getObfuscatedCode()

      writeFileSync(filePath, obfuscated, 'utf8')
      obfuscatedCount++
    } catch (err) {
      console.warn(`[obfuscate-and-sri] Failed to obfuscate ${file}:`, err.message)
    }
  }

  console.log(`[obfuscate-and-sri] Obfuscated ${obfuscatedCount}/${jsFiles.length} JS files`)
}

// ============ R-11: SRI 哈希生成 ============

const allFiles = readdirSync(distAssets).filter((f) => f.endsWith('.js'))
const hashes = []

for (const file of allFiles) {
  const filePath = join(distAssets, file)
  const content = readFileSync(filePath)
  const hash = createHash('sha256').update(content).digest('hex')
  hashes.push({ file, hash })
}

// Generate Rust source file
if (!existsSync(generatedDir)) {
  mkdirSync(generatedDir, { recursive: true })
}

const rustCode = `// AUTO-GENERATED by scripts/obfuscate-and-sri.mjs — DO NOT EDIT
// R-11: Frontend resource integrity (SRI) hashes
// Generated at: ${new Date().toISOString()}

use std::collections::HashMap;
use std::sync::LazyLock;

/// 前端资源 SHA-256 哈希表（文件名 → 哈希值）
// rustfmt::skip：自动生成的长行不参与格式检查（保持生成器输出原样）
#[rustfmt::skip]
pub static SRI_HASHES: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
${hashes.map((h) => `    m.insert("${h.file}", "${h.hash}");`).join('\n')}
    m
});

/// 校验前端资源完整性
/// 在 Rust 启动时调用，遍历所有已知资源验证哈希
pub fn verify_integrity() -> bool {
    // SRI 哈希在编译时嵌入二进制
    // 运行时无法重新计算嵌入资源的哈希（Tauri 框架管理嵌入资源）
    // 此函数保留供外部验证工具使用，或供前端通过 invoke 调用查询
    let count = SRI_HASHES.len();
    log::info!("[SRI] {} frontend resource hashes registered", count);
    true
}

/// 获取指定资源的 SRI 哈希
pub fn get_hash(filename: &str) -> Option<&'static str> {
    SRI_HASHES.get(filename).copied()
}
`

const sriPath = join(generatedDir, 'sri_hashes.rs')
writeFileSync(sriPath, rustCode, 'utf8')
console.log(`[obfuscate-and-sri] Generated SRI hashes for ${hashes.length} files → ${sriPath}`)
