/**
 * characterPack.ts 单元测试
 *
 * 测试 parseCharacterPack 对三种输入格式的统一解析与字段映射。
 *
 * @module characterPack.test
 */
import { describe, it, expect } from 'vitest'
import {
  parseCharacterPack,
  parseCharacterPackFromJSON,
  detectFormat,
  type RawPackConfig,
} from '../characterPack'
import { ATLAS } from '../types'

// ============ 测试数据工厂 ============

/** CharacterPackConfig 格式（characterResourceLoader.ts） */
function makePackConfig(overrides: Partial<RawPackConfig> = {}): RawPackConfig {
  return {
    id: 'test-cat',
    name: 'Test Cat',
    version: '1.0.0',
    author: 'TestAuthor',
    license: 'MIT',
    description: 'A test cat character',
    spritePath: '/pets/test-cat/spritesheet.webp',
    spriteType: 'atlas',
    atlasLayout: { cellW: 192, cellH: 208, cols: 8, rows: 9 },
    themeColor: { primary: '#ff6b6b', secondary: '#4ecdc4' },
    tags: ['cat', 'community'],
    ...overrides,
  }
}

/** CharacterResourcePackage 格式（characterResourceImporter.ts） */
function makeResourcePackage(overrides: Partial<RawPackConfig> = {}): RawPackConfig {
  return {
    meta: {
      id: 'test-dog',
      name: 'test-dog',
      displayName: 'Test Dog',
      version: '1.0.0',
      author: 'TestAuthor',
      license: 'MIT',
      source: 'Community',
      description: 'A test dog character',
      tags: ['dog'],
    },
    sprites: [
      {
        path: '/pets/test-dog/spritesheet.png',
        type: 'atlas',
        layout: { cellW: 192, cellH: 208, cols: 8, rows: 9, animations: {} },
        isShimeji: false,
      },
    ],
    personality: { warmth: 0.7, liveliness: 0.3, dependence: 0.5, directness: -0.2, rationality: 0.1 },
    themeColor: { primary: '#a78bfa', secondary: '#fbbf24' },
    signaturePhrase: '汪汪！',
    classicQuotes: ['我是一只狗'],
    bubbleMessages: {
      idle: ['汪...'],
      hungry: ['饿饿了'],
      sad: ['呜呜'],
      pet: ['好舒服'],
      feed: ['好吃！'],
      pomodoroDone: ['完成！'],
    },
    ...overrides,
  }
}

/** PetMetadata 格式（petMetadata.ts / asset-pipeline 输出） */
function makePetMetadata(overrides: Partial<RawPackConfig> = {}): RawPackConfig {
  return {
    formatVersion: '1.0',
    id: 'test-fox',
    name: 'Test Fox',
    version: '1.0.0',
    author: 'PipelineBot',
    license: 'MIT',
    description: 'A test fox generated by psd_to_pet.py',
    tags: ['fox', 'pipeline'],
    sprite: 'spritesheet.webp',
    spriteType: 'atlas',
    atlas: { cellW: 192, cellH: 208, cols: 8, rows: 9 },
    themeColor: { primary: '#f97316', secondary: '#fb923c' },
    animations: {},
    reactions: {},
    sounds: {},
    personality: { warmth: -0.3, liveliness: 0.8, dependence: 0.2, directness: 0.5, rationality: -0.1 },
    speakingStyle: { tone: 'gentle', wordPreference: 'colloquial', catchphrases: [] },
    defaultSystemPrompt: '你是一只狐狸。',
    compatibility: { spiritpal: '>=0.1.0' },
    ...overrides,
  }
}

// ============ detectFormat 测试 ============

describe('detectFormat', () => {
  it('should detect pack-config format by spritePath', () => {
    const fmt = detectFormat(makePackConfig())
    expect(fmt).toBe('pack-config')
  })

  it('should detect resource-package format by meta + sprites', () => {
    const fmt = detectFormat(makeResourcePackage())
    expect(fmt).toBe('resource-package')
  })

  it('should detect pet-metadata format by formatVersion + sprite', () => {
    const fmt = detectFormat(makePetMetadata())
    expect(fmt).toBe('pet-metadata')
  })

  it('should detect pet-metadata by atlas + sprite without formatVersion', () => {
    const fmt = detectFormat({ sprite: 'sheet.webp', atlas: { cellW: 128, cellH: 128, cols: 8, rows: 9 } })
    expect(fmt).toBe('pet-metadata')
  })

  it('should return unknown for unrecognized format', () => {
    const fmt = detectFormat({ foo: 'bar' })
    expect(fmt).toBe('unknown')
  })

  it('should prioritize resource-package when both meta and spritePath exist', () => {
    // meta takes precedence
    const fmt = detectFormat({ ...makePackConfig(), meta: { id: 'x' } })
    expect(fmt).toBe('resource-package')
  })
})

// ============ parseCharacterPack: CharacterPackConfig 格式 ============

describe('parseCharacterPack: CharacterPackConfig 格式', () => {
  it('should parse all fields correctly', () => {
    const result = parseCharacterPack(makePackConfig())

    expect(result.ok).toBe(true)
    expect(result.profile).not.toBeNull()
    expect(result.profile!.id).toBe('test-cat')
    expect(result.profile!.name).toBe('Test Cat')
    expect(result.profile!.displayName).toBe('Test Cat')
    expect(result.profile!.spriteAsset).toBe('/pets/test-cat/spritesheet.webp')
    expect(result.profile!.spriteType).toBe('atlas')
    expect(result.profile!.atlasLayout).toEqual({ cellW: 192, cellH: 208, cols: 8, rows: 9 })
    expect(result.profile!.themeColor).toEqual({ primary: '#ff6b6b', secondary: '#4ecdc4' })
    expect(result.profile!.source).toBe('TestAuthor')
    expect(result.profile!.birthBackground).toBe('A test cat character')
    expect(result.profile!.type).toBe('community')
  })

  it('should use ATLAS defaults when atlasLayout is missing', () => {
    const result = parseCharacterPack(makePackConfig({ atlasLayout: undefined }))
    expect(result.ok).toBe(true)
    expect(result.profile!.atlasLayout).toEqual({ cellW: ATLAS.cellW, cellH: ATLAS.cellH, cols: ATLAS.cols, rows: ATLAS.rows })
  })

  it('should use author as source when tags is missing', () => {
    const result = parseCharacterPack(makePackConfig({ author: 'CustomAuthor', tags: undefined }))
    expect(result.profile!.source).toBe('CustomAuthor')
  })

  it('should fail when id is missing', () => {
    const result = parseCharacterPack(makePackConfig({ id: undefined }))
    expect(result.ok).toBe(false)
    expect(result.profile).toBeNull()
    expect(result.messages.some((m) => m.level === 'error' && m.field === 'id')).toBe(true)
  })

  it('should auto-set chromaKey for video spriteType', () => {
    const result = parseCharacterPack(makePackConfig({ spriteType: 'video' }))
    expect(result.ok).toBe(true)
    expect(result.profile!.chromaKey).toBe('auto')
    expect(result.messages.some((m) => m.level === 'info' && m.message.includes('chromaKey'))).toBe(true)
  })
})

// ============ parseCharacterPack: CharacterResourcePackage 格式 ============

describe('parseCharacterPack: CharacterResourcePackage 格式', () => {
  it('should parse all fields correctly', () => {
    const result = parseCharacterPack(makeResourcePackage())

    expect(result.ok).toBe(true)
    expect(result.profile).not.toBeNull()
    expect(result.profile!.id).toBe('test-dog')
    expect(result.profile!.name).toBe('test-dog')
    expect(result.profile!.displayName).toBe('Test Dog')
    expect(result.profile!.spriteAsset).toBe('/pets/test-dog/spritesheet.png')
    expect(result.profile!.spriteType).toBe('atlas')
    expect(result.profile!.personality).toEqual({ warmth: 0.7, liveliness: 0.3, dependence: 0.5, directness: -0.2, rationality: 0.1 })
    expect(result.profile!.signaturePhrase).toBe('汪汪！')
    expect(result.profile!.classicQuotes).toEqual(['我是一只狗'])
    expect(result.profile!.bubbleMessages.idle).toEqual(['汪...'])
    expect(result.profile!.bubbleMessages.hungry).toEqual(['饿饿了'])
    expect(result.profile!.source).toBe('Community')
    expect(result.profile!.type).toBe('community')
  })

  it('should use target atlas when isShimeji is true', () => {
    const pkg = makeResourcePackage()
    ;(pkg.sprites as Record<string, unknown>[])[0]!.isShimeji = true
    const result = parseCharacterPack(pkg)

    expect(result.ok).toBe(true)
    expect(result.profile!.atlasLayout).toEqual({ cellW: 192, cellH: 208, cols: 8, rows: 9 })
  })

  it('should normalize webp/png spriteType to atlas', () => {
    const pkg = makeResourcePackage()
    ;(pkg.sprites as Record<string, unknown>[])[0]!.type = 'webp'
    const result = parseCharacterPack(pkg)

    expect(result.ok).toBe(true)
    expect(result.profile!.spriteType).toBe('atlas')
    expect(result.messages.some((m) => m.level === 'info' && m.message.includes('归一化'))).toBe(true)
  })

  it('should warn when sprites array is empty', () => {
    const result = parseCharacterPack(makeResourcePackage({ sprites: [] }))
    expect(result.ok).toBe(true)
    expect(result.messages.some((m) => m.level === 'warning' && m.field === 'sprites')).toBe(true)
  })

  it('should fail when meta.id is missing', () => {
    const pkg = makeResourcePackage()
    ;(pkg.meta as Record<string, unknown>).id = undefined
    const result = parseCharacterPack(pkg)

    expect(result.ok).toBe(false)
    expect(result.profile).toBeNull()
    expect(result.messages.some((m) => m.level === 'error' && m.field === 'meta.id')).toBe(true)
  })
})

// ============ parseCharacterPack: PetMetadata 格式 ============

describe('parseCharacterPack: PetMetadata 格式', () => {
  it('should parse all fields correctly', () => {
    const result = parseCharacterPack(makePetMetadata())

    expect(result.ok).toBe(true)
    expect(result.profile).not.toBeNull()
    expect(result.profile!.id).toBe('test-fox')
    expect(result.profile!.name).toBe('Test Fox')
    expect(result.profile!.displayName).toBe('Test Fox')
    expect(result.profile!.spriteAsset).toBe('spritesheet.webp')
    expect(result.profile!.spriteType).toBe('atlas')
    expect(result.profile!.atlasLayout).toEqual({ cellW: 192, cellH: 208, cols: 8, rows: 9 })
    expect(result.profile!.personality).toEqual({ warmth: -0.3, liveliness: 0.8, dependence: 0.2, directness: 0.5, rationality: -0.1 })
    expect(result.profile!.systemPrompt).toBe('你是一只狐狸。')
    expect(result.profile!.source).toBe('PipelineBot')
    expect(result.profile!.type).toBe('community')
  })

  it('should use ATLAS defaults when atlas is missing', () => {
    const result = parseCharacterPack(makePetMetadata({ atlas: undefined }))
    expect(result.ok).toBe(true)
    expect(result.profile!.atlasLayout).toEqual({ cellW: ATLAS.cellW, cellH: ATLAS.cellH, cols: ATLAS.cols, rows: ATLAS.rows })
  })

  it('should auto-set chromaKey for video type', () => {
    const result = parseCharacterPack(makePetMetadata({ spriteType: 'video' }))
    expect(result.ok).toBe(true)
    expect(result.profile!.chromaKey).toBe('auto')
  })

  it('should use tags joined as source when author is missing', () => {
    const result = parseCharacterPack(makePetMetadata({ author: undefined, tags: ['fox', 'pipeline'] }))
    expect(result.profile!.source).toBe('fox, pipeline')
  })
})

// ============ parseCharacterPack: 通用边界用例 ============

describe('parseCharacterPack: 边界与错误处理', () => {
  it('should fail for null input', () => {
    const result = parseCharacterPack(null)
    expect(result.ok).toBe(false)
    expect(result.profile).toBeNull()
    expect(result.detectedFormat).toBe('unknown')
  })

  it('should fail for array input', () => {
    const result = parseCharacterPack([1, 2, 3])
    expect(result.ok).toBe(false)
    expect(result.profile).toBeNull()
  })

  it('should fail for string input', () => {
    const result = parseCharacterPack('hello')
    expect(result.ok).toBe(false)
    expect(result.profile).toBeNull()
  })

  it('should fail for unrecognized format', () => {
    const result = parseCharacterPack({ foo: 'bar', baz: 123 })
    expect(result.ok).toBe(false)
    expect(result.detectedFormat).toBe('unknown')
    expect(result.messages.some((m) => m.level === 'error' && m.message.includes('无法识别'))).toBe(true)
  })

  it('should warn when spriteAsset is empty', () => {
    const result = parseCharacterPack(makePackConfig({ spritePath: '' }))
    expect(result.ok).toBe(true)
    expect(result.messages.some((m) => m.level === 'warning' && m.field === 'spriteAsset')).toBe(true)
  })

  it('should warn when displayName is empty and use name as fallback', () => {
    const result = parseCharacterPack(makePackConfig({ name: 'fallback-name' }))
    // displayName comes from name in pack-config format
    expect(result.ok).toBe(true)
    expect(result.profile!.displayName).toBe('fallback-name')
  })
})

// ============ parseCharacterPackFromJSON 测试 ============

describe('parseCharacterPackFromJSON', () => {
  it('should parse valid JSON string', () => {
    const json = JSON.stringify(makePackConfig())
    const result = parseCharacterPackFromJSON(json)

    expect(result.ok).toBe(true)
    expect(result.profile!.id).toBe('test-cat')
  })

  it('should fail for invalid JSON string', () => {
    const result = parseCharacterPackFromJSON('{invalid json}')

    expect(result.ok).toBe(false)
    expect(result.profile).toBeNull()
    expect(result.messages.some((m) => m.level === 'error' && m.message.includes('JSON 解析失败'))).toBe(true)
  })

  it('should fail for empty string', () => {
    const result = parseCharacterPackFromJSON('')

    expect(result.ok).toBe(false)
    expect(result.profile).toBeNull()
  })
})
